sonar.organization=tenax-io
sonar.projectKey=tenax-io_tenax-assay
sonar.projectName=tenax-assay
sonar.sources=cli
sonar.tests=tests
sonar.python.coverage.reportPaths=build/coverage.xml
sonar.python.xunit.reportPath=build/junit.xml